version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      time: '03:30'
      timezone: 'Europe/Rome'
      interval: 'daily'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled' # Disable rebasing for npm pull requests
    commit-message:
      prefix: '⬆️ chore'
      include: 'scope'
    groups:
      vite:
        patterns:
          - 'vite*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint*'
      mui:
        patterns:
          - '@mui/material'
          - '@mui/icons-material'
          - '@emotion/*'
      testing-library:
        patterns:
          - '@testing-library/*'
