version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      time: '03:30'
      timezone: 'Europe/Rome'
      interval: 'daily'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled' # Disable rebasing for npm pull requests
    commit-message:
      prefix: '⬆️ chore'
      include: 'scope'
    groups:
      vitest:
        patterns:
          - 'vitest'
          - '@vitest*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint*'
