version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      time: '03:30'
      timezone: 'Europe/Rome'
      interval: 'daily'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled' # Disable rebasing for npm pull requests
    commit-message:
      prefix: '⬆️ chore'
      include: 'scope'
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-router-dom'
          - '@types/react'
          - '@types/react-dom'
      vite:
        patterns:
          - 'vite'
          - 'vite-*'
          - '@vitejs/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest*'
      lint:
        patterns:
          - 'eslint*'
          - '@eslint*'
          - '@typescript-eslint*'
          - 'prettier'
      mui:
        patterns:
          - '@mui/material'
          - '@mui/icons-material'
          - '@emotion/*'
      testing-library:
        patterns:
          - '@testing-library/*'
      lodash:
        patterns:
          - 'lodash*'
          - '@types/lodash*'
