version: '3.8'

services:
  app:
    image: git.m-tartari.eu/m-tartari.github.io
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: m-tartari.github.io
    restart: unless-stopped
    ports:
      - '8080:8080'
