import React from 'react'
import { Typography, Link, List as MuiList, styled, Box } from '@mui/material'

import ListItemText from 'components/atoms/ListItemText/index.js'

const List = styled(MuiList)(({ theme }) => ({
  listStyleType: 'disc',
  paddingLeft: theme.spacing(4),
  '& .MuiListItem-root': {
    display: 'list-item',
    padding: 0,
  },
}))

const PrivacyPolicy: React.FC = () => {
  return (
    <Box aria-labelledby="privacy-policy">
      <Typography id="privacy-policy" aria-label="privacy-policy" variant="h3" component="h2" gutterBottom>
        Privacy Policy
      </Typography>
      <Typography variant="subtitle1" color="textSecondary" component="p" pb={4}>
        Last updated: May 27, 2025
      </Typography>

      <Typography variant="h5" component="h2" gutterBottom>
        Introduction
      </Typography>
      <Typography component="p" color="textSecondary">
        m-tartari ("we", "our", or "us") respects your privacy and is committed to protecting your personal data. This privacy policy will inform you
        about how we look after your personal data when you visit our website and tell you about your privacy rights and how the law protects you.
      </Typography>

      <Typography variant="h5" component="h2" gutterBottom sx={{ mt: 4 }}>
        The Data We Collect About You
      </Typography>
      <Typography component="p" color="textSecondary">
        We collect and process the following information when you visit our website:
      </Typography>
      <List dense>
        <ListItemText title="Technical Data">
          includes internet protocol (IP) address, browser type and version, time zone setting and location, browser plug-in types and versions,
          operating system and platform, and other technology on the devices you use to access this website.
        </ListItemText>
        <ListItemText title="Usage Data"> includes information about how you use our website, products, and services.</ListItemText>
      </List>

      <Typography variant="h5" component="h2" gutterBottom sx={{ mt: 4 }}>
        Cookies
      </Typography>
      <Typography component="p" color="textSecondary">
        We use cookies to distinguish you from other users of our website. This helps us to provide you with a good experience when you browse our
        website and also allows us to improve our site.
      </Typography>
      <Typography component="p" color="textSecondary">
        We use the following types of cookies:
      </Typography>
      <List dense>
        <ListItemText title="Necessary Cookies:">
          These are essential to enable you to use the website and its features. Without these cookies, services you have asked for cannot be
          provided.
        </ListItemText>
        <ListItemText title="Analytics Cookies:">
          We use Google Analytics to help us understand how visitors interact with our website. These cookies collect information about your visit to
          our website, the content you viewed, the links you followed, and information about your browser, device, and IP address. We do this to
          improve how our website works.
        </ListItemText>
      </List>

      <Typography variant="h5" component="h2" gutterBottom sx={{ mt: 4 }}>
        Google Analytics
      </Typography>
      <Typography component="p" color="textSecondary">
        This website uses Google Analytics 4, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to help the
        website analyze how users use the site. The information generated by the cookie about your use of the website will be transmitted to and
        stored by Google on servers in the United States.
      </Typography>
      <Typography component="p" color="textSecondary">
        We have implemented the following measures to be GDPR compliant:
      </Typography>
      <List dense>
        <ListItemText>We have obtained your consent before processing your data through cookies</ListItemText>
        <ListItemText>We have implemented IP address anonymization</ListItemText>
        <ListItemText>We have disabled data sharing with Google</ListItemText>
        <ListItemText>We have set the data retention period to the minimum required for our analysis</ListItemText>
      </List>
      <Typography component="p" color="textSecondary">
        You can prevent the collection of your data by Google Analytics by declining analytics cookies in our cookie consent banner or by using the
        Google Analytics Opt-out Browser Add-on available at{' '}
        <Link color="textPrimary" href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">
          https://tools.google.com/dlpage/gaoptout
        </Link>
        .
      </Typography>

      <Typography variant="h5" component="h2" gutterBottom sx={{ mt: 4 }}>
        Your Rights
      </Typography>
      <Typography component="p" color="textSecondary">
        Under the General Data Protection Regulation (GDPR), you have various rights in relation to your personal data, including:
      </Typography>

      <List dense>
        <ListItemText>The right to access your personal data</ListItemText>
        <ListItemText>The right to rectification of your personal data</ListItemText>
        <ListItemText>The right to erasure of your personal data</ListItemText>
        <ListItemText>The right to restrict processing of your personal data</ListItemText>
        <ListItemText>The right to data portability</ListItemText>
        <ListItemText>The right to object to processing of your personal data</ListItemText>
      </List>

      <Typography variant="h5" component="h2" gutterBottom sx={{ mt: 4 }}>
        Contact Us
      </Typography>
      <Typography component="p" color="textSecondary">
        If you have any questions about this privacy policy or our privacy practices, please contact us at{' '}
        <Link color="textPrimary" href="mailto:privacy@m-tartari.eu" target="_blank" rel="noopener noreferrer">
          privacy@m-tartari.eu
        </Link>
        .
      </Typography>
    </Box>
  )
}

export default PrivacyPolicy
