name: Build
on:
  push:
    branches: ['main']
  pull_request: {}
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # use host's node version https://github.com/actions/setup-node
          # node-version: 'node'
          cache: 'npm'

  build-prod:
    runs-on: ubuntu-latest
    name: Build Production
    needs: setup

    steps:
      - name: Install dependencies
        run: npm ci --omit-dev
      - name: Build
        run: npm run build:prod

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: build-prod

    steps:
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build

    steps:
      - name: Lint
        run: npm run lint

  test-coverage:
    runs-on: ubuntu-latest
    name: Test and Generate Coverage Report
    needs: build

    steps:
      - name: Test and generate coverage report
        run: npm run test:coverage

  upload-coverage:
    runs-on: ubuntu-latest
    name: Upload Coverage Report
    needs: test-coverage

    steps:
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: m-tartari/m-tartari.github.io
